language: php
php:
  - '7.1'
install:
  - composer install
services:
  - redis-server
before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
  - make start-inbuilt-server
script: make test
